// Anchor picker tool for MetaHuman face landmarks.
//
// Loads a MH GLB, lets an operator click anatomical landmarks on the face
// skin, and exports a JSON map of landmark-name to vertex-index in the
// mesh geometry. The output (face_anchors.json) is the MH-side half of
// the MediaPipe-to-MH correspondence used by the live identity warp.
//
// Only records vertex indices, not MediaPipe indices. The MP-side mapping
// is produced separately by running MediaPipe on a reference face and
// picking the nearest landmark per anatomical name.

import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

const DRACO_DECODER = 'https://www.gstatic.com/draco/versioned/decoders/1.5.7/';

// Face-skin landmarks the operator clicks. Ada is symmetrical, so we
// only collect midline and left-side picks; the right-side counterpart
// is auto-generated by mirroring across the mesh's local X=0 plane.
// Order is pick order (top to bottom feels natural).
const LANDMARKS = [
  'forehead_center',
  'left_temple',
  'left_brow_outer',
  'left_brow_middle',
  'left_brow_inner',
  'nasion',
  'nose_bridge_top',
  'left_eye_outer_corner',
  'left_eye_upper_lid',
  'left_eye_inner_corner',
  'left_eye_lower_lid',
  'left_cheekbone',
  'left_cheek_center',
  'nose_tip',
  'left_nostril',
  'subnasale',
  'upper_lip_cupid_left',
  'upper_lip_center',
  'left_lip_corner',
  'lower_lip_center',
  'chin_upper',
  'chin_tip',
  'left_jaw_mid',
  'left_jaw_corner',
  'left_ear_base',
];

// Midline landmarks with no mirror twin. Everything else with a "left_"
// prefix or "_left" suffix gets auto-mirrored to the right side.
function mirroredName(name) {
  if (name.startsWith('left_')) return 'right_' + name.slice(5);
  if (name.endsWith('_left')) return name.slice(0, -5) + '_right';
  return null;
}

const MARKER_MIRROR_COLOR = 0xff8090;

// Meshes whose names contain any of these substrings are considered
// face-skin surfaces (valid pick targets). Everything else (eyeballs,
// teeth, hair cards, cloth) is skipped by the raycaster.
const FACE_MESH_HINTS = ['head', 'face'];
const FACE_MESH_EXCLUDES = ['teeth', 'tongue', 'saliva', 'eye', 'lash', 'brow', 'occlusion'];

const MARKER_COLOR = 0xff4060;
const MARKER_CURRENT_COLOR = 0x60d0ff;
const MARKER_RADIUS = 0.004;

export async function start({ stage, glbUrl, characterId = 'character' }) {
  const state = {
    activeIndex: 0,
    picks: new Map(), // name -> { meshName, vertexIndex, restPosition, marker }
    faceMeshes: [],
    characterId,
  };

  const ui = buildUi(state);

  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(stage.clientWidth, stage.clientHeight);
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  stage.appendChild(renderer.domElement);

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0b0d11);

  const pmrem = new THREE.PMREMGenerator(renderer);
  scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;

  const camera = new THREE.PerspectiveCamera(
    32, stage.clientWidth / stage.clientHeight, 0.01, 20,
  );
  camera.position.set(0, 1.6, 0.6);

  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  // Left button stays free for picking; right-drag orbits, middle zooms.
  controls.mouseButtons = {
    LEFT: null,
    MIDDLE: THREE.MOUSE.DOLLY,
    RIGHT: THREE.MOUSE.ROTATE,
  };
  // Shift+left-drag pans (still leaves plain left-click for picking).
  controls.touches = { ONE: THREE.TOUCH.ROTATE, TWO: THREE.TOUCH.DOLLY_PAN };

  const markerGroup = new THREE.Group();
  scene.add(markerGroup);

  const gltf = await loadGlb(glbUrl);
  scene.add(gltf.scene);
  const candidates = [];
  gltf.scene.traverse((obj) => {
    if (obj.isMesh && isFaceMesh(obj)) candidates.push(obj);
  });
  // Pick the single largest skin mesh by vertex count. MH splits the
  // face into 9 sub-meshes; LOD0_1 is the skin, the rest are lashes,
  // teeth, occlusion, etc. Anchors all need to live on the skin.
  candidates.sort((a, b) =>
    b.geometry.attributes.position.count - a.geometry.attributes.position.count,
  );
  state.faceMeshes = candidates.slice(0, 1);
  _faceMeshesForMirror = state.faceMeshes;
  frameHead(gltf.scene, camera, controls);
  ui.setMeshInfo(state.faceMeshes);
  // Expose for debugging / external resnap scripts.
  window.__picker = { state, scene, camera, faceMeshes: state.faceMeshes };

  const raycaster = new THREE.Raycaster();
  const ndc = new THREE.Vector2();
  attachPicker(renderer.domElement, (ev) => {
    const rect = renderer.domElement.getBoundingClientRect();
    ndc.x = ((ev.clientX - rect.left) / rect.width) * 2 - 1;
    ndc.y = -((ev.clientY - rect.top) / rect.height) * 2 + 1;
    raycaster.setFromCamera(ndc, camera);
    const hits = raycaster.intersectObjects(state.faceMeshes, false);
    if (!hits.length) return;
    const hit = hits[0];
    const pick = vertexFromHit(hit);
    recordPick(state, ui, markerGroup, pick);
  });

  window.addEventListener('resize', () => {
    const w = stage.clientWidth, h = stage.clientHeight;
    renderer.setSize(w, h);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
  });

  (function animate() {
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
  })();

  wireControls(state, ui, markerGroup);

  ui.refresh();
  return { state, scene, camera, renderer };
}

function loadGlb(url) {
  const draco = new DRACOLoader().setDecoderPath(DRACO_DECODER);
  const loader = new GLTFLoader().setDRACOLoader(draco);
  return new Promise((resolve, reject) => {
    loader.load(url, resolve, undefined, reject);
  });
}

function isFaceMesh(mesh) {
  const name = (mesh.name || '').toLowerCase();
  if (FACE_MESH_EXCLUDES.some((s) => name.includes(s))) return false;
  return FACE_MESH_HINTS.some((s) => name.includes(s));
}

function frameHead(root, camera, controls) {
  const box = new THREE.Box3().setFromObject(root);
  const size = box.getSize(new THREE.Vector3());
  const center = box.getCenter(new THREE.Vector3());
  // Aim at roughly where the head sits (top ~15% of bounding box).
  const headY = box.max.y - size.y * 0.12;
  const target = new THREE.Vector3(center.x, headY, center.z);
  const dist = Math.max(size.y, size.x) * 0.6;
  camera.position.set(target.x, target.y, target.z + dist);
  controls.target.copy(target);
  controls.update();
}

// pointerdown/up pair. Treat as a click only if the pointer barely
// moved, so orbit/pan drags do not register as picks.
function attachPicker(el, onClick) {
  let downX = 0, downY = 0, downButton = -1;
  el.addEventListener('pointerdown', (ev) => {
    downX = ev.clientX; downY = ev.clientY; downButton = ev.button;
  });
  el.addEventListener('pointerup', (ev) => {
    if (downButton !== 0 || ev.button !== 0) return;
    const dx = ev.clientX - downX, dy = ev.clientY - downY;
    if (dx * dx + dy * dy > 16) return; // moved > 4px, treat as drag
    onClick(ev);
  });
}

function vertexFromHit(hit) {
  const mesh = hit.object;
  const geom = mesh.geometry;
  const face = hit.face;
  const pos = geom.attributes.position;

  // Nearest of the three triangle vertices (in local space) to the hit point.
  const localHit = mesh.worldToLocal(hit.point.clone());
  const candidates = [face.a, face.b, face.c];
  let bestIdx = candidates[0];
  let bestDist = Infinity;
  const v = new THREE.Vector3();
  for (const i of candidates) {
    v.fromBufferAttribute(pos, i);
    const d = v.distanceToSquared(localHit);
    if (d < bestDist) { bestDist = d; bestIdx = i; }
  }

  v.fromBufferAttribute(pos, bestIdx);
  const restLocal = v.clone();

  return {
    meshName: mesh.name || '(unnamed)',
    vertexIndex: bestIdx,
    restPosition: [restLocal.x, restLocal.y, restLocal.z],
    worldPosition: skinnedWorldPos(mesh, bestIdx),
  };
}

// Rendered world position of vertex `idx` on a SkinnedMesh. For plain
// Mesh, this reduces to matrixWorld * localPos. For SkinnedMesh (MH
// faces), getVertexPosition applies the bone transforms first; the
// result is still in mesh-local space, so we then apply matrixWorld.
function skinnedWorldPos(mesh, idx) {
  const out = new THREE.Vector3();
  if (mesh.isSkinnedMesh && typeof mesh.getVertexPosition === 'function') {
    mesh.getVertexPosition(idx, out);
  } else {
    out.fromBufferAttribute(mesh.geometry.attributes.position, idx);
  }
  return out.applyMatrix4(mesh.matrixWorld);
}

function recordPick(state, ui, markerGroup, pick) {
  const name = LANDMARKS[state.activeIndex];
  replacePick(state, markerGroup, name, pick, MARKER_CURRENT_COLOR);

  // Auto-mirror across local X=0 for any left_* / *_left landmark.
  const mirrorName = mirroredName(name);
  if (mirrorName) {
    const mirrorPick = mirrorPickAcrossX(pick);
    if (mirrorPick) {
      replacePick(state, markerGroup, mirrorName, mirrorPick, MARKER_MIRROR_COLOR);
    }
  }

  // Recolor everything previously picked (not this name or its mirror)
  // back to the default.
  for (const [n, p] of state.picks.entries()) {
    if (n === name) continue;
    if (mirrorName && n === mirrorName) continue;
    if (p.marker) p.marker.material.color.setHex(MARKER_COLOR);
  }

  advanceActive(state, ui);
}

function replacePick(state, markerGroup, name, pick, color) {
  const existing = state.picks.get(name);
  if (existing) markerGroup.remove(existing.marker);
  const marker = makeMarker(pick.worldPosition, color);
  markerGroup.add(marker);
  state.picks.set(name, {
    meshName: pick.meshName,
    vertexIndex: pick.vertexIndex,
    restPosition: pick.restPosition,
    marker,
  });
}

// Find the vertex on the same mesh whose local position is closest to
// the mirrored source position across X=0. Linear scan; one-off per
// click so cost does not matter.
function mirrorPickAcrossX(pick) {
  const mesh = findMeshByNameGlobal(pick.meshName);
  if (!mesh) return null;
  const pos = mesh.geometry.attributes.position;
  const target = new THREE.Vector3(
    -pick.restPosition[0], pick.restPosition[1], pick.restPosition[2],
  );
  const v = new THREE.Vector3();
  let bestIdx = 0, bestDist = Infinity;
  for (let i = 0; i < pos.count; i++) {
    v.fromBufferAttribute(pos, i);
    const d = v.distanceToSquared(target);
    if (d < bestDist) { bestDist = d; bestIdx = i; }
  }
  v.fromBufferAttribute(pos, bestIdx);
  const restLocal = v.clone();
  return {
    meshName: pick.meshName,
    vertexIndex: bestIdx,
    restPosition: [restLocal.x, restLocal.y, restLocal.z],
    worldPosition: skinnedWorldPos(mesh, bestIdx),
  };
}

// Back-reference to the picker's face meshes so mirror lookups can
// resolve without plumbing state through every call site.
let _faceMeshesForMirror = null;
function findMeshByNameGlobal(name) {
  if (!_faceMeshesForMirror) return null;
  for (const m of _faceMeshesForMirror) if (m.name === name) return m;
  return null;
}

function makeMarker(pos, colorHex) {
  const geom = new THREE.SphereGeometry(MARKER_RADIUS, 12, 12);
  const mat = new THREE.MeshBasicMaterial({ color: colorHex, depthTest: false });
  const m = new THREE.Mesh(geom, mat);
  m.position.copy(pos);
  m.renderOrder = 999;
  return m;
}

function advanceActive(state, ui) {
  for (let step = 1; step <= LANDMARKS.length; step++) {
    const next = (state.activeIndex + step) % LANDMARKS.length;
    if (!state.picks.has(LANDMARKS[next])) {
      state.activeIndex = next;
      ui.refresh();
      return;
    }
  }
  // All done: leave active index where it is.
  ui.refresh();
}

function buildUi(state) {
  const listEl = document.getElementById('list');
  const currentEl = document.getElementById('current');
  const meshInfoEl = document.getElementById('meshInfo');

  function refresh() {
    currentEl.textContent = LANDMARKS[state.activeIndex];
    listEl.innerHTML = '';
    LANDMARKS.forEach((name, i) => {
      const li = document.createElement('li');
      li.textContent = name;
      if (state.picks.has(name)) li.classList.add('done');
      if (i === state.activeIndex) li.classList.add('active');
      li.addEventListener('click', () => {
        state.activeIndex = i;
        refresh();
      });
      listEl.appendChild(li);
    });
  }

  function setMeshInfo(faceMeshes) {
    if (!faceMeshes.length) {
      meshInfoEl.innerHTML = '<span style="color:#f88">No face mesh found. Check FACE_MESH_HINTS.</span>';
      return;
    }
    const rows = faceMeshes.map((m) => {
      const count = m.geometry.attributes.position.count;
      return `${m.name}: ${count.toLocaleString()} verts`;
    });
    meshInfoEl.innerHTML = 'Face meshes (pickable):<br>' + rows.join('<br>');
  }

  return { refresh, setMeshInfo };
}

function wireControls(state, ui, markerGroup) {
  document.getElementById('prev').addEventListener('click', () => {
    state.activeIndex = (state.activeIndex - 1 + LANDMARKS.length) % LANDMARKS.length;
    ui.refresh();
  });
  document.getElementById('next').addEventListener('click', () => {
    state.activeIndex = (state.activeIndex + 1) % LANDMARKS.length;
    ui.refresh();
  });
  document.getElementById('clear').addEventListener('click', () => {
    const name = LANDMARKS[state.activeIndex];
    clearOne(state, markerGroup, name);
    const mirror = mirroredName(name);
    if (mirror) clearOne(state, markerGroup, mirror);
    ui.refresh();
  });
  document.getElementById('download').addEventListener('click', () => {
    // Emit the clicked names in pick order, then any auto-mirrored twins
    // immediately after their source. Keeps the JSON grouped logically.
    const ordered = [];
    for (const n of LANDMARKS) {
      if (state.picks.has(n)) ordered.push(n);
      const mirror = mirroredName(n);
      if (mirror && state.picks.has(mirror)) ordered.push(mirror);
    }
    const payload = {
      version: 1,
      characterId: state.characterId,
      anchors: ordered.map((n) => {
        const p = state.picks.get(n);
        return {
          name: n,
          meshName: p.meshName,
          vertexIndex: p.vertexIndex,
          restPosition: p.restPosition,
        };
      }),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'face_anchors.json';
    a.click();
    URL.revokeObjectURL(a.href);
  });
  document.getElementById('load').addEventListener('click', () => {
    document.getElementById('loadFile').click();
  });
  document.getElementById('loadFile').addEventListener('change', async (ev) => {
    const file = ev.target.files[0];
    if (!file) return;
    const text = await file.text();
    const data = JSON.parse(text);
    // The picker now constrains to the skin mesh (LOD0_1) only, so any
    // anchor saved against a different sub-mesh (eyelash, occlusion, etc.)
    // gets resnapped to the nearest skin vertex at the same local
    // position. Print a summary so the operator knows which moved.
    const skin = state.faceMeshes[0];
    const resnapped = [];
    for (const a of data.anchors || []) {
      if (state.picks.has(a.name)) {
        clearOne(state, markerGroup, a.name);
      }
      let entry;
      if (a.meshName === skin.name) {
        entry = { ...a };
      } else {
        const snap = nearestVertOnMesh(skin, a.restPosition);
        entry = {
          name: a.name,
          meshName: skin.name,
          vertexIndex: snap.vertexIndex,
          restPosition: snap.restPosition,
        };
        resnapped.push({ name: a.name, from: a.meshName, dist: snap.dist });
      }
      const world = skinnedWorldPos(skin, entry.vertexIndex);
      const marker = makeMarker(world, MARKER_COLOR);
      markerGroup.add(marker);
      state.picks.set(a.name, { ...entry, marker });
    }
    if (resnapped.length) {
      console.log('[anchor-picker] resnapped to skin:', resnapped);
    }
    ui.refresh();
  });
}

function findMeshByName(meshes, name) {
  for (const m of meshes) if (m.name === name) return m;
  return null;
}

// Nearest vertex on `mesh` to an arbitrary local-space position. Used
// when hydrating anchors saved against a different sub-mesh.
function nearestVertOnMesh(mesh, restPos) {
  const pos = mesh.geometry.attributes.position;
  const target = new THREE.Vector3(restPos[0], restPos[1], restPos[2]);
  const v = new THREE.Vector3();
  let bestIdx = 0, bestDist = Infinity;
  for (let i = 0; i < pos.count; i++) {
    v.fromBufferAttribute(pos, i);
    const d = v.distanceToSquared(target);
    if (d < bestDist) { bestDist = d; bestIdx = i; }
  }
  v.fromBufferAttribute(pos, bestIdx);
  return {
    vertexIndex: bestIdx,
    restPosition: [v.x, v.y, v.z],
    dist: Math.sqrt(bestDist),
  };
}

function clearOne(state, markerGroup, name) {
  const existing = state.picks.get(name);
  if (!existing) return;
  markerGroup.remove(existing.marker);
  existing.marker.geometry.dispose();
  existing.marker.material.dispose();
  state.picks.delete(name);
}
